---
- name: Include Variable file
  become: true
  include_vars:
   dir: 'vars'
   files_matching: 'target_server_vars.yml'

- name: Copy files to target machine
  #fetch: src=/Softwares/Installers/mq_iib/tester.txt dest=./files/#
  when: invetory_hostname == "NB5CG8183YYM.metmom.mmih.biz"
  shell: scp /Softwares/Installers/mq_iib/tester.txt '{{ target_id }}@{{ targethost }}':/tools/IBM/


