---
- name: Include Variable file
  become: true
  include_vars:
   dir: 'vars'
   files_matching: 'target_server_vars.yml'

- name: Copy files to target machine
  when: inventroy_hostname == "NB5CG8183YYM.metmom.mmih.biz"
  fetch: src=/Softwares/Installers/mq_iib/ dest=/tools/IBM/
  delegate_to: "{{ targethost }}"

