---
- name: Include Variable file
  include_vars:
   dir: 'vars'
   files_matching: 'target_server_vars.yml'

- name: Copy files to target machine 
  become: true
  synchronize:
   mode: pull
   group: yes
   owner: yes
   perms: yes
   recursive: yes
   src: /Softwares/Installers/mq_iib/
   dest: /tools/IBM/
  delegate_to: "{{ targethost }}"
  register: view
  
- debug: var=view  


