---
- name: Include Variable file
  become: true
  include_vars:
   dir: 'vars'
   files_matching: 'target_server_vars.yml'

- name: Copy files to target machine
  become_user: itumeleng
  fetch: src=/Softwares/Installers/mq_iib/ dest=./file remote_src=yes
  delegate_to: "{{ targethost }}"

